// Code generated by gotypegen. DO NOT EDIT.

//////////
// source: models.go

/**
 * InternalToolsConfig controls which built-in tools are enabled for an agent
 */
export interface InternalToolsConfig {
  plan?: boolean;
  memory?: boolean;
  widget?: boolean;
  finish?: boolean;
  skills?: boolean;
  host_context?: boolean;
}
/**
 * AgentTool represents a unified tool that can be used by an agent
 */
export interface AgentTool {
  name: string;
  display_name?: string;
  description: string;
  type: string;
  require_approval?: boolean;
  app?: AppToolConfig;
  agent?: AgentToolConfig;
  hook?: HookToolConfig;
  http?: HTTPToolConfig;
  call?: HTTPToolConfig;
  mcp?: MCPToolConfig;
  client?: ClientToolConfig;
  internal?: InternalToolConfig;
}
/**
 * InternalToolConfig contains configuration for internal/built-in tools
 */
export interface InternalToolConfig {
  category: string;
  operation: string;
}
/**
 * SkillConfig defines a skill available to the agent.
 */
export interface SkillConfig {
  name: string;
  description: string;
  skill_id?: string;
  version_id?: string;
  url?: string;
  content?: string;
  preload?: boolean;
}
/**
 * ContextField declares a context parameter expected by the agent.
 */
export interface ContextField {
  name: string;
  description?: string;
  required?: boolean;
  default?: string;
}
export interface AppToolConfig {
  ref: string;
  id?: string;
  version_id?: string;
  function?: string;
  session_enabled?: boolean;
  setup?: any;
  input?: any;
}
export interface AgentToolConfig {
  ref: string;
  id?: string;
  version_id?: string;
}
export interface HookToolConfig {
  url: string;
  secret?: string;
  input_schema?: any;
  output_schema?: any;
}
export interface ClientToolConfig {
  input_schema?: any;
  output_schema?: any;
}
/**
 * ToolAuthConfig declares how a tool authenticates.
 */
export interface ToolAuthConfig {
  type: string;
  provider?: string;
  integration_id?: string;
  secret?: string;
  header?: string;
}
export interface HTTPToolConfig {
  url: string;
  method?: string;
  auth?: ToolAuthConfig;
  headers?: { [key: string]: string};
  input_schema?: any;
  output_schema?: any;
}
export interface MCPToolConfig {
  integration_id: string;
  tool_name: string;
}
/**
 * AgentConfigInput is the API input shape for agent version config.
 * Mirrors AgentConfig's JSON contract without gorm tags or runtime pointers.
 */
export interface AgentConfigInput {
  name?: string;
  description?: string;
  system_prompt?: string;
  example_prompts?: string[];
  core_app?: CoreAppConfigInput;
  tools?: (AgentTool | undefined)[];
  skills?: SkillConfig[];
  context?: ContextField[];
  internal_tools?: InternalToolsConfig;
  output_schema?: any;
}
/**
 * CoreAppConfigInput is the API input shape for core app configuration.
 */
export interface CoreAppConfigInput {
  id?: string;
  version_id?: string;
  ref?: string;
  setup?: any;
  input?: any;
}
export interface APIResponse<T extends any> {
  success: boolean;
  status: number /* int */;
  data: T;
  error?: APIError;
}
export interface APIError {
  code: string;
  message: string;
  suggestions?: string[];
  meta?: { [key: string]: any};
}
/**
 * ApiAppRunRequest is the request body for /apps/run endpoint.
 */
export interface ApiAppRunRequest {
  app?: string;
  app_id?: string;
  version_id?: string;
  infra?: Infra;
  workers?: string[];
  webhook?: string;
  setup?: any;
  input: any;
  stream?: boolean;
  wait?: boolean;
  function?: string;
  session?: string;
  session_timeout?: number /* int */;
  run_at?: string;
  metadata?: TaskMetadata;
}
/**
 * ApiAgentRunRequest is the request body for /agents/run endpoint.
 */
export interface ApiAgentRunRequest {
  chat_id?: string;
  agent?: string;
  agent_config?: AgentConfigInput;
  agent_name?: string;
  input: ChatTaskInput;
  context?: { [key: string]: string};
  stream?: boolean;
}
export interface SkillPublishRequest {
  namespace?: string;
  name: string;
  description: string;
  category: string;
  repo_url: string;
  license: string;
  allowed_tools: string;
  compatibility: string;
  instructions: string;
  files: KnowledgeFile[];
  metadata?: { [key: string]: string};
  parent_skill_id?: string;
  parent_version_id?: string;
  source_url?: string;
  version_notes?: string;
  disable_model_invocation: boolean;
  user_invocable?: boolean;
  context: string;
}
/**
 * KnowledgeFile represents a file in a knowledge entry
 */
export interface KnowledgeFile {
  path: string;
  uri?: string;
  size: number /* int64 */;
  hash: string;
  content?: string;
}
export type ChatMessageRole = string;
export const ChatMessageRoleSystem: ChatMessageRole = "system";
export const ChatMessageRoleUser: ChatMessageRole = "user";
export const ChatMessageRoleAssistant: ChatMessageRole = "assistant";
export const ChatMessageRoleTool: ChatMessageRole = "tool";
/**
 * ChatTaskInput is the input envelope for a chat LLM task
 */
export interface ChatTaskInput {
  model?: string;
  context_size: number /* int */;
  temperature?: number /* float64 */;
  top_p?: number /* float64 */;
  reasoning_effort?: string;
  reasoning_max_tokens?: number /* int */;
  system_prompt: string;
  context: ChatTaskContextMessage[];
  role?: ChatMessageRole;
  text?: string;
  reasoning?: string;
  /**
   * Attachments is the SDK input field with full file metadata
   */
  attachments?: FileRef[];
  /**
   * Images and Files are internal fields for task workers (filled from Attachments or context)
   */
  images?: string[];
  files?: string[];
  tools?: Tool[];
  tool_call_id?: string;
}
/**
 * ChatTaskContextMessage represents a message in the chat context for LLM tasks
 */
export interface ChatTaskContextMessage {
  role: ChatMessageRole;
  text?: string;
  reasoning?: string;
  images?: string[];
  files?: string[];
  tools?: Tool[];
  tool_calls?: ToolCall[];
  tool_call_id?: string;
}
export type StringEncodedMap = { [key: string]: any};
/**
 * Infra defines where a task should run.
 */
export type Infra = string;
export const InfraPrivate: Infra = "private";
export const InfraCloud: Infra = "cloud";
export const InfraPrivateFirst: Infra = "private_first";
/**
 * TaskAction defines an action to execute when a task reaches a specific status.
 */
export interface TaskAction {
  key: string;
  on: string;
  params?: any;
}
/**
 * TaskMetadata holds optional metadata attached to a task.
 */
export interface TaskMetadata {
  action?: TaskAction;
}
/**
 * ToolCall represents a tool call from an LLM response (wire format)
 * This is a transport object for parsing LLM responses, not a database model
 */
export interface ToolCall {
  id: string;
  type: string; // "function"
  function: ToolCallFunction;
}
/**
 * ToolCallFunction contains the function name and arguments from an LLM tool call
 */
export interface ToolCallFunction {
  name: string;
  arguments: StringEncodedMap;
}
/**
 * FileRef is a lightweight reference to a file with essential metadata.
 * Used in chat inputs/context instead of full File objects.
 */
export interface FileRef {
  id?: string;
  uri: string;
  filename: string;
  content_type: string;
  size?: number /* int64 */;
}
/**
 * Tool represents a tool definition for LLM function calling
 */
export interface Tool {
  type: string;
  function: ToolFunction;
}
export interface ToolFunction {
  name: string;
  description: string;
  parameters?: ToolParameters;
  required?: string[];
}
export interface ToolParameters {
  type: string;
  title: string;
  properties?: ToolParameterProperties;
  required?: string[];
}
export type ToolParameterProperties = { [key: string]: ToolParameterProperty};
export interface ToolParameterProperty {
  type: string;
  title: string;
  description: string;
  properties?: ToolParameterProperties;
  items?: ToolParameterProperty;
  required?: string[];
}
